services:
  radio-aggregator:
    build: .
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - AGGREGATE_STREAM_KEY
      - AGGREGATE_STREAM_LIFETIME
      - INGESTOR_STREAM_KEYS_KEY
