services:
  flight-server:
    build: api-gateway
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
  flight-ui:
    build: flight-ui
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
