services:
  api-gateway:
    build: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - flight-ui
  flight-ui:
    build: flight-ui
    depends_on:
      - flight-api
      - flight-events
  flight-api:
    build: flight-api
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
  flight-events:
    build: flight-events
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - STREAM_KEY
  radio-consumer:
    build: radio-consumer
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - STREAM_KEY
      - AIRCRAFT_DATA_LIFETIME
