services:
  radio-ingestor:
    build: .
    environment:
      - SBS1_SOURCE_HOST=host.docker.internal
      - SBS1_SOURCE_PORT=30003
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - INGESTOR_STREAM_KEY
      - INGESTOR_STREAM_KEYS_KEY
      - INGESTOR_STREAM_LIFETIME
